<a href="https://colab.research.google.com/github/Rama-Has/Poem_Generator_Rama_Hasiba_12010022/blob/main/Arabic_Poem_Generator_NLP_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

--------------------------------------------
> # Arabic Poem Generator  




In [ ]:
# %tensorflow_version 1.x
# !pip install -q gpt-2-simple
import gpt_2_simple as gpt2
from datetime import datetime
from google.colab import files

In [ ]:
gpt2.download_gpt2(model_name="124M")

Fetching checkpoint: 1.05Mit [00:00, 332Mit/s]                                                      
Fetching encoder.json: 1.05Mit [00:00, 5.78Mit/s]
Fetching hparams.json: 1.05Mit [00:00, 791Mit/s]                                                    
Fetching model.ckpt.data-00000-of-00001: 498Mit [00:09, 54.9Mit/s]                                  
Fetching model.ckpt.index: 1.05Mit [00:00, 613Mit/s]                                                
Fetching model.ckpt.meta: 1.05Mit [00:00, 5.43Mit/s]
Fetching vocab.bpe: 1.05Mit [00:00, 6.39Mit/s]


In [ ]:
# gpt2.mount_gdrive()

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount = True) 

Mounted at /content/drive


In [2]:
!unzip -q "/content/drive/MyDrive/Arabic Poem Comprehensive Dataset (APCD).zip" -d "/content/"

replace /content/Arabic Poem Comprehensive Dataset (APCD).csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y


In [2]:
import pandas as pd  
data = pd.read_csv("/content/Arabic Poem Comprehensive Dataset (APCD).csv")
data

العصر             الشاعر          الديوان القافية   البحر  \
0        قبل الإسلام  عمرو بنِ قُمَيئَة  الديوان الرئيسي       د  الطويل   
1        قبل الإسلام  عمرو بنِ قُمَيئَة  الديوان الرئيسي       د  الطويل   
2        قبل الإسلام  عمرو بنِ قُمَيئَة  الديوان الرئيسي       د  الطويل   
3        قبل الإسلام  عمرو بنِ قُمَيئَة  الديوان الرئيسي       د  الطويل   
4        قبل الإسلام  عمرو بنِ قُمَيئَة  الديوان الرئيسي       د  الطويل   
...              ...                ...              ...     ...     ...   
1831765       الحديث          شهاب غانم        شهاب غانم       ن  الخفيف   
1831766       الحديث          شهاب غانم        شهاب غانم       ن  الخفيف   
1831767       الحديث          شهاب غانم        شهاب غانم       ن  الخفيف   
1831768       الحديث          شهاب غانم        شهاب غانم       ن  الخفيف   
1831769       الحديث          شهاب غانم        شهاب غانم       ن  الخفيف   

                                  الشطر الايسر  \
0         وَأَن تَجمَعا شَملي وَتَنتَظِرا غَدا   
1        وَلا سُرعَتي يَوماً بِسابِقَةِ الرَدى   
2        وَتَستَوجِبا مَنّاً عَلَيَّ وَتُحمَدا   
3          تُؤامِرُني سِرّاً لِأَصرِمَ مَرثَدا   
4         وَأَفرَعَ في لَومي مِراراً وَأَصعَدا   
...                                        ...   
1831765                    وأحلى قصيدة تَتَغنى   
1831766                كحلم يغشى الجفون الوسنى   
1831767                يتداعى وجداً ويخفق حسنا   
1831768                 يدك الحدود سجناً فسجنا   
1831769                 آه لو أدرك الغرام لجنا   

                                   الشطر الايمن  \
0         خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا   
1           فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ   
2        وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً   
3            لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ   
4          وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ   
...                                         ...   
1831765        هي أغلى ما أنشأ اللَّه في الدنيا   
1831766                هي أغرودة الأغاريد تنساب   
1831767                      هي شلال بهجة وبهاء   
1831768             هي حلم الهوى ومنطلقي الباقي   
1831769                 هي حبي العاتي وكل غرامي   

                                                     البيت  
0        خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا    وَأَن...  
1        فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ    وَلا سُ...  
2        وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً    وَتَ...  
3        لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ    تُؤامِرُ...  
4        وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ    وَأَفر...  
...                                                    ...  
1831765  هي أغلى ما أنشأ اللَّه في الدنيا    وأحلى قصيد...  
1831766  هي أغرودة الأغاريد تنساب    كحلم يغشى الجفون ا...  
1831767      هي شلال بهجة وبهاء    يتداعى وجداً ويخفق حسنا  
1831768  هي حلم الهوى ومنطلقي الباقي    يدك الحدود سجنا...  
1831769  هي حبي العاتي وكل غرامي    آه لو أدرك الغرام لجنا  

[1831770 rows x 8 columns]

In [3]:
data = data[['البيت']]
data

البيت
0        خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا    وَأَن...
1        فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ    وَلا سُ...
2        وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً    وَتَ...
3        لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ    تُؤامِرُ...
4        وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ    وَأَفر...
...                                                    ...
1831765  هي أغلى ما أنشأ اللَّه في الدنيا    وأحلى قصيد...
1831766  هي أغرودة الأغاريد تنساب    كحلم يغشى الجفون ا...
1831767      هي شلال بهجة وبهاء    يتداعى وجداً ويخفق حسنا
1831768  هي حلم الهوى ومنطلقي الباقي    يدك الحدود سجنا...
1831769  هي حبي العاتي وكل غرامي    آه لو أدرك الغرام لجنا

[1831770 rows x 1 columns]

In [4]:
print(f"There are a atotal of {data.shape[0]} poem line in the dataset, I'll use the first 12 000 sample only")

There are a atotal of 1831770 poem line in the dataset, I'll use the first 12 000 sample only


In [7]:
poems_lines = data['البيت'].to_list()[: 50000]
poems_lines[0: 5]

['خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا    وَأَن تَجمَعا شَملي وَتَنتَظِرا غَدا',
 'فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ    وَلا سُرعَتي يَوماً بِسابِقَةِ الرَدى',
 'وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً    وَتَستَوجِبا مَنّاً عَلَيَّ وَتُحمَدا',
 'لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ    تُؤامِرُني سِرّاً لِأَصرِمَ مَرثَدا',
 'وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ    وَأَفرَعَ في لَومي مِراراً وَأَصعَدا']

In [8]:
import re
# remove special characters
ARABIC_PUNCTUATION = '''`÷×؛<>_()*&^%][ـ،/:"؟.,'{}~¦+|!”…“–ـ'''

def remove_arabic_punctuation(text: str):
    translator = str.maketrans('', '', ARABIC_PUNCTUATION)
    cleaned_text = text.translate(translator)
    return cleaned_text

def remove_multiple_spaces(text):
    cleaned_text = re.sub(' +', ' ', text)
    return cleaned_text

In [9]:
# !pip install pyarabic

In [10]:
# For arabic diacritics 
from pyarabic.araby import strip_tashkeel

### Data Cleanning:
  1. Remove strips
  2. Remove arabic punctuation
  3. Remove multiple spaces

In [10]:
poems_lines = [strip_tashkeel(line) for line in poems_lines]
poems_lines = [remove_arabic_punctuation(line) for line in poems_lines]
poems_lines = [remove_multiple_spaces(line) for line in poems_lines]

In [11]:
poems_lines[0: 5]

['خليلي لا تستعجلا أن تزودا وأن تجمعا شملي وتنتظرا غدا',
 'فما لبث يوما بسابق مغنم ولا سرعتي يوما بسابقة الردى',
 'وإن تنظراني اليوم أقض لبانة وتستوجبا منا علي وتحمدا',
 'لعمرك ما نفس بجد رشيدة تؤامرني سرا لأصرم مرثدا',
 'وإن ظهرت منه قوارص جمة وأفرع في لومي مرارا وأصعدا']

In [12]:
# !pip install transformers

# Finetune GPT-2

In [13]:
#  data[['البيت']].head(12000).copy()

In [14]:
poems_lines_df = data[['البيت']].head(30000).copy()
poems_lines_df['البيت'] = poems_lines_df['البيت'].map(remove_arabic_punctuation)
poems_lines_df['البيت'] = poems_lines_df['البيت'].map(strip_tashkeel)
poems_lines_df['البيت'] = poems_lines_df['البيت'].map(remove_multiple_spaces)

In [22]:
poems_lines_df = data[['البيت']].head(50000).copy()

In [23]:
poems_lines_df.to_csv(r'arabic_full_text.txt', header=None, index=None, sep=' ', mode='a')

In [24]:
file_path = '/content/arabic_full_text.txt'

In [25]:
from transformers import TextDataset, DataCollatorForLanguageModeling

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
train, test = train_test_split(poems_lines_df.head(50000), test_size=0.15, shuffle=False)

In [28]:
train.shape

(42500, 1)

In [29]:
train.columns

Index(['البيت'], dtype='object')

In [30]:
test.shape

(7500, 1)

In [31]:
train.to_csv(r'train_dataset.txt', header=None, index=None, sep=' ', mode='a')
test.to_csv(r'test_dataset.txt', header=None, index=None, sep=' ', mode='a')

In [32]:
train.head(3)

البيت
4042   وَالعارُ مَضّاضٌ وَلَيسَ بِخائِفٍ    مِن حَتفِ...
1378   وَتُضحي الحُصونُ المُشمَخِرّاتُ في الذُرى    و...
36951  لَم يَبقَ مِنهُم بَعدَهُم    إِلّا حَديثٌ أَو ...

In [33]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("aubmindlab/aragpt2-base")

train_path = '/content/train_dataset.txt'
test_path = '/content/test_dataset.txt'

In [34]:
def load_dataset(train_path,test_path,tokenizer):
    train_dataset = TextDataset(
          tokenizer=tokenizer,
          file_path=train_path,
          block_size=128)

    test_dataset = TextDataset(
          tokenizer=tokenizer,
          file_path=test_path,
          block_size=128)

    data_collator = DataCollatorForLanguageModeling(
        tokenizer=tokenizer, mlm=False,
    )
    return train_dataset,test_dataset,data_collator

In [35]:
train_dataset,test_dataset,data_collator = load_dataset(train_path,test_path,tokenizer)


from transformers import Trainer, TrainingArguments, AutoModelWithLMHead


/usr/local/lib/python3.10/dist-packages/transformers/data/datasets/language_modeling.py:53: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py
  warnings.warn(


In [28]:
# !pip install --upgrade accelerate

In [72]:
# !pip install git+https://github.com/huggingface/accelerate


In [29]:
# !pip install transformers==4.28.0


In [50]:
model = AutoModelWithLMHead.from_pretrained("aubmindlab/aragpt2-base")

training_args = TrainingArguments(
    output_dir = "./gpt2-araPoems", #The output directory
    overwrite_output_dir = True, #overwrite the content of the output directory
    num_train_epochs = 15, # number of training epochs
    per_device_train_batch_size=32, # batch size for training
    per_device_eval_batch_size=64,  # batch size for evaluation
    eval_steps = 400, # Number of update steps between two evaluations.
    save_steps=800, # after # steps model is saved
    warmup_steps=500,# number of warmup steps for learning rate scheduler
    )

trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

In [51]:
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


TrainOutput(global_step=660, training_loss=6.18901025020715, metrics={'train_runtime': 811.2851, 'train_samples_per_second': 25.681, 'train_steps_per_second': 0.814, 'total_flos': 1361004871680000.0, 'train_loss': 6.18901025020715, 'epoch': 15.0})

In [53]:
trainer.save_model('./aragpt_model__15_epoch')

from google.colab import files
import shutil

# Compress the folder into a zip file
shutil.make_archive("/content/aragpt_model__15_epoch", "zip", "/content/aragpt_model__15_epoch")


'/content/aragpt_model__15_epoch.zip'

In [41]:
from transformers import pipeline

In [54]:
generator_ = pipeline('text-generation', model='./aragpt_model__15_epoch', tokenizer='aubmindlab/aragpt2-base')

In [61]:
max_words = 50  # Set the desired maximum number of words

result = generator_('الليل ', max_length = 60)[0]['generated_text']

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.


In [62]:
print(result)

الليل يبيتون على الفوارس والأسياف"
"إذا لم يكن من الدهر إلا أن يكون في الناس مواهبه وأن تكون الدنيا عنده غمام"
لما انجلت عنه الشمس عن وجهه حتى أضاءت منه ضوء النهار"
ألا يا ابن أبي العاصي إن


In [40]:
data

البيت
0        خَليلَيَّ لا تَستَعجِلا أَن تَزَوَّدا    وَأَن...
1        فَما لَبَثٌ يَوماً بِسابِقٍ مَغنَمٍ    وَلا سُ...
2        وَإِن تُنظِراني اليَومَ أَقضِ لُبانَةً    وَتَ...
3        لَعَمرُكَ ما نَفسٌ بِجِدٍ رَشيدَةٍ    تُؤامِرُ...
4        وَإِن ظَهَرَت مِنهُ قَوارِصُ جَمَّةٌ    وَأَفر...
...                                                    ...
1831765  هي أغلى ما أنشأ اللَّه في الدنيا    وأحلى قصيد...
1831766  هي أغرودة الأغاريد تنساب    كحلم يغشى الجفون ا...
1831767      هي شلال بهجة وبهاء    يتداعى وجداً ويخفق حسنا
1831768  هي حلم الهوى ومنطلقي الباقي    يدك الحدود سجنا...
1831769  هي حبي العاتي وكل غرامي    آه لو أدرك الغرام لجنا

[1831770 rows x 1 columns]

In [ ]:
# sess = gpt2.start_tf_sess()

# gpt2.finetune(sess,
#               dataset= " \n".join(poems_lines),
#               model_name='124M',
#               steps=2000,
#               restore_from='fresh',
#               run_name='run1',
#               print_every=50,
#               sample_every=200,
#               save_every=500
#               )

In [ ]:
# import gpt_2_simple as gpt2

# import tensorflow as tf
# Download the GPT-2 model (run only once)
# gpt2.download_gpt2(model_name='124M')

# Load the fine-tuning data
# data_path = 'path/to/your/preprocessed_data.txt'  # Replace with the path to your preprocessed data
# # Clear the TensorFlow graph
# # Clear the TensorFlow graph
# tf.compat.v1.reset_default_graph()
# sess = gpt2.start_tf_sess()
# gpt2.finetune(sess,
#               dataset = poems_lines[0: 12000],
#               model_name='124M',
#               steps=1000)

# # Save the fine-tuned model
# gpt2.save_model(sess, './aragpt2')

# # Generate text using the fine-tuned model
# generated_text = gpt2.generate(sess, prefix='الليل', length=100)
# print(generated_text)


--------------------------------------------
# **Another solution**

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount = True) 

Mounted at /content/drive


In [ ]:
import numpy as np
# import torch
# from torch import nn
# import torch.nn.functional as F

## Load Data

In [ ]:
# open text file and read in data as `text`
with open('/content/all_data.txt', 'r',encoding="utf-8") as f:
    text = f.read()

In [ ]:
text[:100]

'بدت تختال في حُلل الجمالِ\n\nوجادت بالزيارة والوصال\n\nتميس فلا يعادلها قضيب\n\nوإن ترنو تداعب بالنصال\n\nبم'

## Tokenization

In [ ]:
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in text])

In [ ]:
encoded[:100]

array([21, 10, 34, 38, 34, 39, 34, 23, 31, 38, 44, 52, 38, 68, 22, 31, 31,
       38, 23, 31,  3, 14, 23, 31, 73, 75, 75, 16,  3, 23, 10, 34, 38, 21,
       23, 31, 62, 52, 23, 47, 11, 38, 16, 23, 31, 16, 51, 23, 31, 75, 75,
       34, 14, 52,  4, 38, 44, 31, 23, 38, 52, 40, 23, 10, 31, 27, 23, 38,
       74, 67, 52, 21, 75, 75, 16, 79, 76, 38, 34, 47, 76, 16, 38, 34, 10,
       23, 40, 21, 38, 21, 23, 31, 76, 51, 23, 31, 75, 75, 21, 14])

## Pre-processing the data

in char-RNN, the LSTM expects an input that is one-hot encoded for more about one-hot-encoding, check out this post

In [ ]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [ ]:
def get_batches(arr, batch_size, seq_length):

    batch_size_total = batch_size * seq_length
    # total number of batches we can make
    n_batches = len(arr)//batch_size_total
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size_total]
    # Reshape into batch_size rows
    arr = arr.reshape((batch_size, -1))
    
    # iterate through the array, one sequence at a time
    for n in range(0, arr.shape[1], seq_length):
        # The features
        x = arr[:, n:n+seq_length]
        # The targets, shifted by one
        y = np.zeros_like(x)
        try:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+seq_length]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
        yield x, y

## Visualise the output

let's try to get batches out of the 100 character of encoded data and see what's happening

In [ ]:
batches = get_batches(encoded, 8, 50)
x, y = next(batches)
# printing out the first 10 items in a sequence
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[21 10 34 38 34 39 34 23 31 38]
 [76 29 38 14 23 38 68 23 31 34]
 [51 29 68 29 16 76 23 38 44 29]
 [47 74 22 38 23 31 40 22 52 16]
 [44 29 17 29 76 61 29 17 16 23]
 [17 47 67 73 38  0 29 76 62 23]
 [27 23 76 22 27 23 75 75 68 34]
 [16 27  3 47 34 27 38 31 23 38]]

y
 [[10 34 38 34 39 34 23 31 38 44]
 [29 38 14 23 38 68 23 31 34 73]
 [29 68 29 16 76 23 38 44 29 17]
 [74 22 38 23 31 40 22 52 16 76]
 [29 17 29 76 61 29 17 16 23 38]
 [47 67 73 38  0 29 76 62 23 65]
 [23 76 22 27 23 75 75 68 34 53]
 [27  3 47 34 27 38 31 23 38 34]]


## Defining the network

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive', force_remount = True) 

In [ ]:
import tensorflow as tf

# Define the model architecture
vocab_size = 82
hidden_units = 512
num_layers = 5
dropout_rate = 0.5

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, hidden_units),
    tf.keras.layers.LSTM(hidden_units, return_sequences=True, dropout=dropout_rate, recurrent_dropout=dropout_rate),
    tf.keras.layers.Dropout(dropout_rate),
    tf.keras.layers.Dense(vocab_size)
])

# Compile the model
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer='adam',
              metrics=['accuracy'])


In [ ]:
model.fit(encoded,,epochs=100, verbose=1)